apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: team-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ${ACR_NAME}.azurecr.io/alpha-app/frontend:${IMAGE_TAG}
          ports:
            - containerPort: 80

